stages:
  preprocess_bioasq_mesh:
    cmd: grants_tagger preprocess bioasq-mesh data/raw/allMeSH_2021.json data/processed/train_mesh2021.jsonl
        models/xlinear/label_binarizer.pkl --test-split 0.01 --test-output-path data/processed/test_mesh2021.jsonl
    deps:
    - data/raw/allMeSH_2021.json
    - grants_tagger/preprocess_mesh.py
    outs:
    - data/processed/train_mesh2021.jsonl
    - data/processed/test_mesh2021.jsonl
    - models/xlinear/label_binarizer.pkl
  preprocess_bioasq_mesh_toy:  # Creates toy data to help iterating/testing code
      cmd: grants_tagger preprocess bioasq-mesh data/raw/allMeSH_2021.json data/processed/train_mesh2021_toy.jsonl
        models/label_binarizer_toy.pkl --test-split 0.01 --test-output-path data/processed/test_mesh2021_toy.jsonl
        --n-max 1000
      deps:
        - data/raw/allMeSH_2021.json
        - grants_tagger/preprocess_mesh.py
      outs:
        - data/processed/train_mesh2021_toy.jsonl
        - data/processed/test_mesh2021_toy.jsonl
        - models/label_binarizer_toy.pkl
  train_mesh_xlinear:
    cmd: grants_tagger train data/processed/train_mesh2021.jsonl
      --approach mesh-xlinear --sparse-labels --train-info results/mesh_xlinear_train_info.json --slim
    deps:
    - data/processed/train_mesh2021.jsonl
    - grants_tagger/train.py
    - grants_tagger/slim/mesh_xlinear.py
    params:
    - train.mesh-xlinear.config
    outs:
    - models/xlinear/model-2022.9.0
  evaluate_mesh_xlinear:
    cmd: grants_tagger evaluate model mesh-xlinear models/xlinear/model-2022.9.0
      data/processed/test_mesh2021.jsonl models/xlinear/label_binarizer-2022.9.0.pkl
      --results-path results/mesh_xlinear.json
      --full-report-path results/mesh_xlinear_full_report.json --no-split-data
    deps:
    - grants_tagger/evaluate_model.py
    - models/xlinear/model-2022.9.0
    - models/xlinear/label_binarizer-2022.9.0.pkl
    metrics:
    - results/mesh_xlinear.json:
        cache: false
  filter_mesh_tags:
    cmd: python grants_tagger/filter_mesh_tags.py data/raw/desc2021.xml data/processed/mesh_disease_tags.csv
    deps:
    - data/raw/desc2021.xml
    outs:
    - data/processed/mesh_disease_tags.csv
  evaluate_mesh_xlinear_on_grants:
    cmd: grants_tagger evaluate grants mesh-xlinear models/xlinear/model-2022.9.0
      data/raw/disease_tags_validation_grants.xlsx models/xlinear/label_binarizer-2022.9.0.pkl
      --results-path results/mesh_xlinear_on_grants.json
      --mesh-tags-path data/processed/mesh_disease_tags.csv
    deps:
    - data/raw/disease_tags_validation_grants.xlsx
    - data/processed/mesh_disease_tags.csv
    - grants_tagger/evaluate_mesh_on_grants.py
    - models/xlinear/model-2022.9.0
    - models/xlinear/label_binarizer-2022.9.0.pkl
    metrics:
    - results/mesh_xlinear_on_grants.json:
        cache: false
