stages:
  preprocess_wellcome_science:
    cmd: grants_tagger preprocess wellcome-science data/raw/science_tags_full_version.xlsx
      data/processed/science_grants_tagged_title_synopsis.jsonl
    deps:
    - data/raw/science_tags_full_version.xlsx
    - grants_tagger/preprocess.py
    params:
    - preprocess_wellcome_science.text_cols
    - preprocess_wellcome_science.meta_cols
    outs:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
  train_tfidf_svm:
    cmd: grants_tagger train data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl models/tfidf-svm-2020.05.2.pkl --approach tfidf-svm
    deps:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
    - grants_tagger/train.py
    params:
    - train.tfidf-svm.tfidf.min_df
    - train.tfidf-svm.svm__estimator.class_weight
    - train.tfidf-svm.tfidf.ngram_range
    outs:
    - models/label_binarizer.pkl
    - models/tfidf-svm-2020.05.2.pkl
  evaluate_tfidf_svm:
    cmd: grants_tagger evaluate model tfidf-svm models/tfidf-svm-2020.05.2.pkl data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl --results-path results/tfidf_svm.json
    deps:
    - grants_tagger/evaluate_model.py
    - models/label_binarizer.pkl
    - models/tfidf-svm-2020.05.2.pkl
    metrics:
    - results/tfidf_svm.json:
        cache: false
  train_scibert:
    cmd: grants_tagger train data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl models/scibert-2020.05.5 --approach scibert
    deps:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
    - grants_tagger/train.py
    params:
    - train.scibert.validation_split
    - train.scibert.learning_rate
    - train.scibert.epochs
  evaluate_scibert:
    cmd: grants_tagger evaluate model scibert models/scibert-2020.05.5 data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl --results-path results/scibert.json
    deps:
    - grants_tagger/evaluate_model.py
    - models/label_binarizer.pkl
    - models/scibert-2020.05.5
    metrics:
    - results/scibert.json:
        cache: false
  train_science_ensemble:
    cmd: grants_tagger train data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl models/science_ensemble --approach science-ensemble
    deps:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
    - grants_tagger/train.py
    params:
    - train.tfidf-svm.tfidf.min_df
    - train.tfidf-svm.svm__estimator.class_weight
    - train.tfidf-svm.tfidf.ngram_range
    - train.scibert.validation_split
    - train.scibert.learning_rate
    - train.scibert.epochs
    outs:
    - models/science_ensemble 
  preprocess_bioasq_mesh:
    cmd: grants_tagger preprocess bioasq-mesh data/raw/allMeSH_2020.json data/processed/mesh2020.jsonl
    deps:
    - data/raw/allMeSH_2020.json
    - grants_tagger/preprocess_mesh.py
    outs:
    - data/processed/diseas_mesh.jsonl
  train_mesh_tfidf_svm:
    cmd: grants_tagger train data/processed/disease_mesh.jsonl
      models/disease_mesh_label_binarizer.pkl models/disease_mesh_tfidf-svm-2020.07.0
      --aproach tfidf-sgd
    deps:
    - data/processed/disease_mesh.jsonl
    - grants_tagger/train.py
    - grants_tagger/models.py
    params:
    - train.mesh-tfidf-svm.tfidf.ngram_range
    - train.mesh-tfidf-svm.tfidf.max_features
    - train.mesh-tfidf-svm.svm__estimator.loss
    - train.mesh-tfidf-svm.svm__estimator.alpha
    - train.mesh-tfidf-svm.model_path
    outs:
    - models/disease_mesh_tfidf-svm-2020.07.0
  train_mesh_cnn:
    cmd: grants_tagger train data/processed/disease_mesh.jsonl
      models/disease_mesh_label_binarizer.pkl models/disease_mesh_cnn-2021.03.0
      --aproach mesh-cnn --sparse-labels
    deps:
    - data/processed/disease_mesh.jsonl
    - grants_tagger/train.py
    - grants_tagger/models.py
    params:
    - train.mesh-cnn.vec.tokenizer_library
    - train.mesh-cnn.vec.vocab_size
    - train.mesh-cnn.vec.sequence_length
    - train.mesh-cnn.cnn.attention
    - train.mesh-cnn.cnn.multilabel
    - train.mesh-cnn.cnn.l2
    - train.mesh-cnn.cnn.hidden_size
    - train.mesh-cnn.cnn.dense_size
    - train.mesh-cnn.cnn.batch_size
    - train.mesh-cnn.cnn.learning_rate
    - train.mesh-cnn.cnn.learning_rate_decay
    - train.mesh-cnn.cnn.nb_epochs
    - train.mesh-cnn.cnn.dropout
    outs:
    - models/disease_mesh_cnn-2021.03.0
