stages:
  preprocess_wellcome_science:
    cmd: grants_tagger preprocess wellcome-science data/raw/science_tags_full_version.xlsx
      data/processed/science_grants_tagged_title_synopsis.jsonl
    deps:
    - data/raw/science_tags_full_version.xlsx
    - grants_tagger/preprocess.py
    params:
    - preprocess_wellcome_science.text_cols
    - preprocess_wellcome_science.meta_cols
    outs:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
  train_tfidf_svm:
    cmd: grants_tagger train data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl models/tfidf-svm-2020.05.2.pkl --approach tfidf-svm
    deps:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
    - grants_tagger/train.py
    params:
    - train.tfidf-svm.tfidf.min_df
    - train.tfidf-svm.svm__estimator.class_weight
    - train.tfidf-svm.tfidf.ngram_range
    outs:
    - models/label_binarizer.pkl
    - models/tfidf-svm-2020.05.2.pkl
  preprocess_bioasq_mesh:
    cmd: grants_tagger preprocess bioasq-mesh data/raw/allMeSH_2020.json data/processed/mesh2020.jsonl
    deps:
    - data/raw/allMeSH_2020.json
    - grants_tagger/preprocess_mesh.py
    outs:
    - data/processed/mesh2020.jsonl
  evaluate_tfidf_svm:
    cmd: grants_tagger evaluate model tfidf-svm models/tfidf-svm-2020.05.2.pkl data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl
    deps:
    - grants_tagger/evaluate_model.py
    - models/label_binarizer.pkl
    - models/tfidf-svm-2020.05.2.pkl
    metrics:
    - results.json:
        cache: false
