preprocess_wellcome_science:
  text_cols: "Title,Synopsis"
  meta_cols: "Grant_ID,Title"
train:
  tfidf-svm:
    tfidf:
      min_df: 5
      ngram_range: [1,2]
    svm__estimator:
      class_weight: "balanced"
  scibert:
    validation_split: 0.10
    learning_rate: 0.00002
    epochs: 10
  mesh-tfidf-svm:
    model_path: models/disease_mesh_tfidf-svm-2020.07.0
    tfidf:
      ngram_range: [1,2]
      max_features: 2_000_000
    svm__estimator:
      loss: "log"
      alpha: 1e-9
preprocess_bioasq_mesh:
  filter_tags: "disease"
  mesh_metadata_path: "data/raw/desc2020.xml"
