preprocess_wellcome_science:
  text_cols: "Title,Synopsis"
  meta_cols: "Grant_ID,Title"
preprocess_bioasq_mesh:
  mesh_tags_path: null
train:
  # 2020.05.2
  tfidf-svm:
    tfidf:
      min_df: 5
      ngram_range: [1,2]
    svm__estimator:
      class_weight: "balanced"
  # 2020.05.5
  scibert:
    validation_split: 0.10
    learning_rate: 0.00002
    epochs: 10
  # 2022.3.0
  mesh-xlinear:
    #tfidf params
    max_features: 400_000
    ngram_range: [1,1]
    #xlinear params
    vectorizer_library: "pecos"
    cluster_chain: True
    beam_size: 30
    only_topk: 200
    min_weight_value: 0.1

