vars:
    - data: "../../data/"
    - models: "../../models/"

stages:
    prepare_data:
        cmd: |
            python prepare_data.py ${data}/processed/train_mesh2021.jsonl ${data}/processed/bertmesh/X.npy ${data}/processed/bertmesh/Y.npz ${models}/bertmesh/label_binarizer.pkl --years ${prepare_data.years} --pretrained-model ${train.pretrained_model}
            python prepare_data.py ${data}/processed/train_mesh2021.jsonl ${data}/processed/bertmesh/X_test.npy ${data}/processed/bertmesh/Y_test.npz ${models}/bertmesh/label_binarizer.pkl --years ${prepare_data.test_years} --pretrained-model ${train.pretrained_model}
        deps:
        - prepare_data.py
        params:
        - prepare_data.years
        - train.pretrained_model
        outs:
        - ${data}/processed/bertmesh/X.npy
        - ${data}/processed/bertmesh/Y.npz
        - ${data}/processed/bertmesh/X_test.npy
        - ${data}/processed/bertmesh/Y_test.npz
        - ${models}/bertmesh/label_binarizer.pkl
    train:
        cmd: python train_torch.py ${data}/processed/bertmesh/X.npy ${data}/processed/bertmesh/Y.npz ${models}/bertmesh/model.pt
            --learning-rate ${train.learning_rate} --batch-size ${train.batch_size} --epochs ${train.epochs} 
            --pretrained-model ${train.pretrained_model} --multilabel-attention --hidden-size ${train.hidden_size}
            --clip-norm ${train.clip_norm} --dropout ${train.dropout}
        deps:
        - train.py
        - ${data}/processed/bertmesh/X.npy
        - ${data}/processed/bertmesh/Y.npz
        - ${models}/bertmesh/label_binarizer.pkl
        params:
        - train.learning_rate
        - train.epochs
        - train.batch_size
        - train.pretrained_model
        - train.hidden_size
        - train.clip_norm
        - train.dropout
        outs:
        - ${models}/bertmesh/model.pt
    evaluate:
        cmd: python evaluate.py ${data}/processed/bertmesh/X_test.npy ${data}/processed/bertmesh/Y_test.npz ${models}/bertmesh/model.pt --results-path results.json
        deps:
        - evaluate.py
        - ${data}/processed/bertmesh/X_test.npy
        - ${data}/processed/bertmesh/Y_test.npz
        - ${models}/bertmesh/model.pt
        metrics:
        - results.json:
            cache: false
