# Github action to run black and open a PR
# https://github.com/explosion/spaCy/blob/master/.github/workflows/autoblack.yml

name: autoblack
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 5'

jobs:
  autoblack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v1
      - run: |
          pip install black
          pip install dvc
      - name: Auto format code if needed
        run: |
          black grants_tagger
          dvc commit
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: Auto format code with black
          commit-message: Auto format code with black
          committer: GitHub <noreply@github.com>
          author: nsorros <nsorros@users.noreply.github.com>
          branch: autoblack
          delete-branch: true
          draft: false
