# Github action that runs flake8 check

name: flake8-check
on: pull_request
jobs:
  flake8-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 --ignore E501,F401,W503,E203,F811,E402 grants_tagger
