vars:
- data: ../../data/processed/xtransformer
- models: ../../models/xtransformer

stages:
    preprocess:
        cmd: |
            python prepare_data.py ../../data/processed/train_mesh2021.jsonl ${data}/X.npz ${data}/Y.npz ${models}/tfidf_vectorizer.pkl ${models}/label_binarizer.pkl --x-txt-path ${data}/X.txt --years 2018,2019
            python prepare_data.py ../../data/test_mesh2021.jsonl ${data}/X_test.npz ${data}/Y_test.npz ${models}/tfidf_vectorizer.pkl ${models}/label_binarizer.pkl --x-txt-path ${data}/X_test.txt --years 2020,2021
        deps:
        - ../../data/processed/train_mesh2021.jsonl
        - ../../data/processed/test_mesh2021.jsonl
        params:
        - prepare
        outs:
        - ${data}/X.npz
        - ${data}/Y.npz
        - ${data}/X.txt
        - ${data}/X_test.npz
        - ${data}/Y_test.npz
        - ${data}/X_test.txt
    train:
        cmd: python -m pecos.xmc.xtransformer.train --trn-text-path ${data}/X.txt --trn-feat-path ${data}/X.npz --trn-label-path ${data}/Y.npz --model-dir ${models} 
            --batch-size ${train.batch_size} --learning-rate ${train.learning_rate} --num-train-epochs ${train.epochs} --gradient-accumulation-steps ${train.gradient_accumulation_steps}
        deps:
        - ${data}/X.txt
        - ${data}/X.npz
        - ${data}/Y.npz
        params:
        - train
        outs:
        - ${models}
    evaluate:
        cmd: |
            python -m pecos.xmc.xtransformer.predict --text-path ${data}/X_test.txt --feat-path ${data}/X_test.npz --label-path ${data}/Y.npz --model-folder ${models} --output-dir ${data}
            python evaluate.py ${data}/Y_test.npz ${data}/P.npz --results-path results.json
        deps:
        - ${data}/X_test.txt
        - ${data}/X_test.npz
        - ${data}/Y_test.npz
        metrics:
        - results.json:
            cache: false
